# Generated by Django 6.0.6 on 2026-06-04 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=5)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('place_of_birth', models.CharField(max_length=200)),
                ('complete_address', models.TextField()),
                ('barangay', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], max_length=20)),
                ('contact_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Format: +63XXXXXXXXXX', regex='^\\+63\\d{10}$')])),
                ('osca_id_number', models.CharField(max_length=50, unique=True)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deceased', 'Deceased'), ('Transferred', 'Transferred')], default='Active', max_length=20)),
            ],
        ),
    ]
