# Generated by Django 6.0.6 on 2026-06-04 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='barangay',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='civil_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], default='Single', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='contact_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^\\+63\\d{10}$')]),
        ),
    ]
