# Generated by Django 6.0.6 on 2026-06-09 00:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_member_barangay_alter_member_civil_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('ADD', 'Added Record'), ('EDIT', 'Edited Record'), ('DELETE', 'Deleted Record'), ('ID_VERIFY', 'ID Validated'), ('BENEFIT_UPDATE', 'Benefits Altered')], max_length=20)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeniorCitizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthdate', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_validated', models.BooleanField(default=False)),
                ('id_processed_date', models.DateTimeField(blank=True, null=True)),
                ('has_pension', models.BooleanField(default=False)),
                ('has_sss', models.BooleanField(default=False)),
                ('has_philhealth', models.BooleanField(default=False)),
                ('has_medical_assistance', models.BooleanField(default=False)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='dashboard.barangay')),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
