# Generated by Django 6.0.6 on 2026-06-09 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_barangay_memberlog_seniorcitizen_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorcitizen',
            name='phone_number',
            field=models.CharField(default='+630000000000', max_length=13, validators=[django.core.validators.RegexValidator(message='Format: +639XXXXXXXXX', regex='^\\+63[0-9]{10}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memberlog',
            name='action',
            field=models.CharField(max_length=20),
        ),
    ]
