# Generated by Django 6.0.6 on 2026-06-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_seniorcitizen_phone_number_alter_memberlog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seniorcitizen',
            name='id_validated',
        ),
        migrations.AddField(
            model_name='seniorcitizen',
            name='id_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='seniorcitizen',
            name='id_type',
            field=models.CharField(choices=[('SSS', 'SSS'), ('PHILHEALTH', 'PhilHealth'), ('GSIS', 'GSIS'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
    ]
