# Generated by Django 6.0.6 on 2026-06-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_seniorcitizen_id_validated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorcitizen',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
