# Generated by Django 6.0.6 on 2026-06-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_seniorcitizen_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorcitizen',
            name='address',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='seniorcitizen',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='seniorcitizen',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
