# Generated by Django 6.0.6 on 2026-06-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_seniorcitizen_address_seniorcitizen_middle_initial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seniorcitizen',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='seniorcitizen',
            name='id_processed_date',
        ),
        migrations.RemoveField(
            model_name='seniorcitizen',
            name='id_type',
        ),
        migrations.AlterField(
            model_name='barangay',
            name='name',
            field=models.CharField(choices=[('Amas', 'Amas'), ('Amazion', 'Amazion'), ('Balabag', 'Balabag'), ('Balindog', 'Balindog'), ('Binoligan', 'Binoligan'), ('Birada', 'Birada'), ('Gayola', 'Gayola'), ('Ginatilan', 'Ginatilan'), ('Ilomavis', 'Ilomavis'), ('Indangan', 'Indangan'), ('Junction', 'Junction'), ('Kalaisan', 'Kalaisan'), ('Kalasuyan', 'Kalasuyan'), ('Katipunan', 'Katipunan'), ('Lanao', 'Lanao'), ('Linangcob', 'Linangcob'), ('Luvimin', 'Luvimin'), ('Macebolig', 'Macebolig'), ('Magsaysay', 'Magsaysay'), ('Malinan', 'Malinan'), ('Manongol', 'Manongol'), ('Marbel', 'Marbel'), ('Mateo', 'Mateo'), ('Meohao', 'Meohao'), ('Mua-an', 'Mua-an'), ('New Bohol', 'New Bohol'), ('Nuangan', 'Nuangan'), ('Onica', 'Onica'), ('Paco', 'Paco'), ('Patadon', 'Patadon'), ('Perez', 'Perez'), ('Poblacion', 'Poblacion'), ('San Isidro', 'San Isidro'), ('San Roque', 'San Roque'), ('Santo Niño', 'Santo Niño'), ('Sibawan', 'Sibawan'), ('Sikitan', 'Sikitan'), ('Singao', 'Singao'), ('Sudapin', 'Sudapin'), ('Sumbao', 'Sumbao')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='seniorcitizen',
            name='address',
            field=models.CharField(default='Not specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='seniorcitizen',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seniorcitizen',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
