# Generated by Django 6.0.6 on 2026-07-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_seniorcitizen_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorcitizen',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
