# Generated by Django 6.0.6 on 2026-07-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_seniorcitizen_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seniorcitizen',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DECEASED', 'Deceased')], default='ACTIVE', max_length=10),
        ),
    ]
