# Generated by Django 6.0.6 on 2026-07-03 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_seniorcitizen_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorcitizen',
            name='civil_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], default='Single', max_length=10),
        ),
        migrations.AlterField(
            model_name='seniorcitizen',
            name='date_registered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
