# Generated by Django 6.0.6 on 2026-07-06 04:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_seniorcitizen_civil_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seniorcitizen',
            name='date_registered',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='seniorcitizen',
            name='id_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seniorcitizen',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DECEASED', 'Deceased')], default='ACTIVE', max_length=10, null=True),
        ),
    ]
