# Generated by Django 6.0.6 on 2026-07-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_seniorcitizen_date_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorcitizen',
            name='id_type',
            field=models.CharField(choices=[('SSS', 'SSS'), ('PHILHEALTH', 'PhilHealth'), ('SENIOR', 'Senior Citizen'), ('MEDICAL', 'Medical')], default='SENIOR', max_length=20),
        ),
    ]
