# Generated by Django 6.0.6 on 2026-07-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_seniorcitizen_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seniorcitizen',
            name='id_type',
            field=models.CharField(choices=[('SSS', 'SSS'), ('PHILHEALTH', 'PhilHealth'), ('PENSION', 'Pension'), ('MEDICAL', 'Medical')], default='PENSION', max_length=20),
        ),
    ]
