# Generated by Django 6.0.5 on 2026-05-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('date_registered', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SeniorCitizen',
        ),
    ]
