# Generated by Django 6.0.5 on 2026-05-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_member_delete_seniorcitizen'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
