# Generated by Django 6.0.5 on 2026-05-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_member_is_active_alter_member_date_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
            preserve_default=False,
        ),
    ]
