# Generated by Django 6.0.5 on 2026-05-29 01:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_member_birth_date_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_registered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
