# Generated by Django 6.0.5 on 2026-05-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_member_date_registered_alter_member_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='barangay',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_registered',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
