# Generated by Django 6.0.5 on 2026-05-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_member_is_active_member_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date_registered',
        ),
        migrations.RemoveField(
            model_name='member',
            name='gender',
        ),
        migrations.AlterField(
            model_name='member',
            name='barangay',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
