# Generated by Django 6.0.5 on 2026-05-29 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_member_date_registered_remove_member_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
    ]
