# Generated by Django 6.0.5 on 2026-05-29 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_barangay_memberlog_seniorcitizen_delete_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorcitizen',
            name='has_medical_assistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seniorcitizen',
            name='has_pension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seniorcitizen',
            name='has_philhealth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seniorcitizen',
            name='has_sss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seniorcitizen',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='seniorcitizen',
            name='id_processed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seniorcitizen',
            name='id_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='memberlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('ADD', 'Added Record'), ('EDIT', 'Edited Record'), ('DELETE', 'Deleted Record'), ('ID_VERIFY', 'ID Validated'), ('BENEFIT_UPDATE', 'Benefits Altered')], max_length=20),
        ),
        migrations.AlterField(
            model_name='memberlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
